/* eslint-disable @typescript-eslint/no-require-imports -- Metro needs static requires for bundled animation files. */
export const galleryItems = [
  { id: 0, name: 'Smiley', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/smiley.gif'), deviceData: require('../../assets/device-animations/smiley.motif') },
  { id: 1, name: 'Crimson Eye', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/itachi.gif'), deviceData: require('../../assets/device-animations/itachi.motif') },
  { id: 2, name: 'Rorschach', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/goat.gif'), deviceData: require('../../assets/device-animations/goat.motif') },
  { id: 3, name: '50 Year', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/50-year-gif.gif'), deviceData: require('../../assets/device-animations/50-year-gif.motif') },
  { id: 4, name: 'Omnitrix', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/omnitrix.gif'), deviceData: require('../../assets/device-animations/omnitrix.motif') },
  { id: 5, name: 'Japan', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/japan.gif'), deviceData: require('../../assets/device-animations/japan.motif') },
  { id: 6, name: 'BIM', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/bim.gif'), deviceData: require('../../assets/device-animations/bim.motif') },
  { id: 7, name: 'Quiet', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/quiet.gif'), deviceData: require('../../assets/device-animations/quiet.motif') },
  { id: 8, name: 'Level Ten', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/level-ten.gif'), deviceData: require('../../assets/device-animations/level-ten.motif') },
  { id: 9, name: 'Nocta', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/nocta.gif'), deviceData: require('../../assets/device-animations/nocta.motif') },
  { id: 10, name: 'Fleur', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/fleur.gif'), deviceData: require('../../assets/device-animations/fleur.motif') },
  { id: 11, name: 'Quiet Red', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/quiet-red.gif'), deviceData: require('../../assets/device-animations/quiet-red.motif') },
  { id: 12, name: 'Challenger', category: 'Emblems', framed: true, image: require('../../assets/device-gifs/challenger.gif'), deviceData: require('../../assets/device-animations/challenger.motif') },
  { id: 13, name: '100', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-100.gif'), deviceData: require('../../assets/device-animations/noto-100.motif') },
  { id: 14, name: 'Alien Monster', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-alien-monster.gif'), deviceData: require('../../assets/device-animations/noto-alien-monster.motif') },
  { id: 15, name: 'Alien', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-alien.gif'), deviceData: require('../../assets/device-animations/noto-alien.motif') },
  { id: 16, name: 'Basketball', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-basketball.gif'), deviceData: require('../../assets/device-animations/noto-basketball.motif') },
  { id: 17, name: 'Beating Heart', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-beating-heart.gif'), deviceData: require('../../assets/device-animations/noto-beating-heart.motif') },
  { id: 18, name: 'Bomb', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-bomb.gif'), deviceData: require('../../assets/device-animations/noto-bomb.motif') },
  { id: 19, name: 'Broken Heart', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-broken-heart.gif'), deviceData: require('../../assets/device-animations/noto-broken-heart.motif') },
  { id: 20, name: 'Chequered Flag', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-chequered-flag.gif'), deviceData: require('../../assets/device-animations/noto-chequered-flag.motif') },
  { id: 21, name: 'Clown', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-clown.gif'), deviceData: require('../../assets/device-animations/noto-clown.motif') },
  { id: 22, name: 'Collision', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-collision.gif'), deviceData: require('../../assets/device-animations/noto-collision.motif') },
  { id: 23, name: 'Cowboy', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-cowboy.gif'), deviceData: require('../../assets/device-animations/noto-cowboy.motif') },
  { id: 24, name: 'Crown', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-crown.gif'), deviceData: require('../../assets/device-animations/noto-crown.motif') },
  { id: 25, name: 'Cyclone', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-cyclone.gif'), deviceData: require('../../assets/device-animations/noto-cyclone.motif') },
  { id: 26, name: 'Dragon', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-dragon.gif'), deviceData: require('../../assets/device-animations/noto-dragon.motif') },
  { id: 27, name: 'Eye', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-eye.gif'), deviceData: require('../../assets/device-animations/noto-eye.motif') },
  { id: 28, name: 'Eyes', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-eyes.gif'), deviceData: require('../../assets/device-animations/noto-eyes.motif') },
  { id: 29, name: 'Fire Heart', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-fire-heart.gif'), deviceData: require('../../assets/device-animations/noto-fire-heart.motif') },
  { id: 30, name: 'Fire', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-fire.gif'), deviceData: require('../../assets/device-animations/noto-fire.motif') },
  { id: 31, name: 'Fox Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-fox-face.gif'), deviceData: require('../../assets/device-animations/noto-fox-face.motif') },
  { id: 32, name: 'Ghost', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-ghost.gif'), deviceData: require('../../assets/device-animations/noto-ghost.motif') },
  { id: 33, name: 'Glowing Star', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-glowing-star.gif'), deviceData: require('../../assets/device-animations/noto-glowing-star.motif') },
  { id: 34, name: 'Grin Sweat', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-grin-sweat.gif'), deviceData: require('../../assets/device-animations/noto-grin-sweat.motif') },
  { id: 35, name: 'Heart Eyes', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-heart-eyes.gif'), deviceData: require('../../assets/device-animations/noto-heart-eyes.motif') },
  { id: 36, name: 'Hot Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-hot-face.gif'), deviceData: require('../../assets/device-animations/noto-hot-face.motif') },
  { id: 37, name: 'Imp Smile', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-imp-smile.gif'), deviceData: require('../../assets/device-animations/noto-imp-smile.motif') },
  { id: 38, name: 'Lion Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-lion-face.gif'), deviceData: require('../../assets/device-animations/noto-lion-face.motif') },
  { id: 39, name: 'Metal', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-metal.gif'), deviceData: require('../../assets/device-animations/noto-metal.motif') },
  { id: 40, name: 'Mind Blown', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-mind-blown.gif'), deviceData: require('../../assets/device-animations/noto-mind-blown.motif') },
  { id: 41, name: 'Moon Face Full', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-moon-face-full.gif'), deviceData: require('../../assets/device-animations/noto-moon-face-full.motif') },
  { id: 42, name: 'Motorcycle', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-motorcycle.gif'), deviceData: require('../../assets/device-animations/noto-motorcycle.motif') },
  { id: 43, name: 'Muscle', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-muscle.gif'), deviceData: require('../../assets/device-animations/noto-muscle.motif') },
  { id: 44, name: 'Musical Notes', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-musical-notes.gif'), deviceData: require('../../assets/device-animations/noto-musical-notes.motif') },
  { id: 45, name: 'Party Popper', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-party-popper.gif'), deviceData: require('../../assets/device-animations/noto-party-popper.motif') },
  { id: 46, name: 'Police Car Light', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-police-car-light.gif'), deviceData: require('../../assets/device-animations/noto-police-car-light.motif') },
  { id: 47, name: 'Racing Car', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-racing-car.gif'), deviceData: require('../../assets/device-animations/noto-racing-car.motif') },
  { id: 48, name: 'Rage', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-rage.gif'), deviceData: require('../../assets/device-animations/noto-rage.motif') },
  { id: 49, name: 'Red Heart', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-red-heart.gif'), deviceData: require('../../assets/device-animations/noto-red-heart.motif') },
  { id: 50, name: 'Robot', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-robot.gif'), deviceData: require('../../assets/device-animations/noto-robot.motif') },
  { id: 51, name: 'Rocket', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-rocket.gif'), deviceData: require('../../assets/device-animations/noto-rocket.motif') },
  { id: 52, name: 'Rolling Eyes', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-rolling-eyes.gif'), deviceData: require('../../assets/device-animations/noto-rolling-eyes.motif') },
  { id: 53, name: 'Skull', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-skull.gif'), deviceData: require('../../assets/device-animations/noto-skull.motif') },
  { id: 54, name: 'Smiley Cat', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-smiley-cat.gif'), deviceData: require('../../assets/device-animations/noto-smiley-cat.motif') },
  { id: 55, name: 'Soccer Ball', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-soccer-ball.gif'), deviceData: require('../../assets/device-animations/noto-soccer-ball.motif') },
  { id: 56, name: 'Sparkles', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-sparkles.gif'), deviceData: require('../../assets/device-animations/noto-sparkles.motif') },
  { id: 57, name: 'Star Struck', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-star-struck.gif'), deviceData: require('../../assets/device-animations/noto-star-struck.motif') },
  { id: 58, name: 'Sun With Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-sun-with-face.gif'), deviceData: require('../../assets/device-animations/noto-sun-with-face.motif') },
  { id: 59, name: 'Sunglasses Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-sunglasses-face.gif'), deviceData: require('../../assets/device-animations/noto-sunglasses-face.motif') },
  { id: 60, name: 'Tiger', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-tiger.gif'), deviceData: require('../../assets/device-animations/noto-tiger.motif') },
  { id: 61, name: 'Trophy', category: 'Motion', framed: false, image: require('../../assets/device-gifs/noto-trophy.gif'), deviceData: require('../../assets/device-animations/noto-trophy.motif') },
  { id: 62, name: 'Unicorn', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-unicorn.gif'), deviceData: require('../../assets/device-animations/noto-unicorn.motif') },
  { id: 63, name: 'Victory', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-victory.gif'), deviceData: require('../../assets/device-animations/noto-victory.motif') },
  { id: 64, name: 'Warning', category: 'Symbols', framed: false, image: require('../../assets/device-gifs/noto-warning.gif'), deviceData: require('../../assets/device-animations/noto-warning.motif') },
  { id: 65, name: 'Zany Face', category: 'Characters', framed: false, image: require('../../assets/device-gifs/noto-zany-face.gif'), deviceData: require('../../assets/device-animations/noto-zany-face.motif') },
  { id: 66, name: 'Toyota Ember', category: 'Emblems', framed: true, image: require('../../assets/animation-masters/toyota-ember/toyota-ember.webp'), deviceData: require('../../assets/device-animations/toyota-ember.motif') },
  { id: 67, name: 'Loading', category: 'Motion', framed: true, image: require('../../assets/device-animations/motif-loading-preview.png'), deviceData: require('../../assets/device-animations/motif-loading.motif') },
  { id: 68, name: 'Badge Loading', category: 'Motion', framed: true, image: require('../../assets/device-animations/badge-loading.webp'), deviceData: require('../../assets/device-animations/badge-loading.motif') },
  { id: 69, name: 'Prism Vortex', category: 'Motion', framed: true, image: require('../../assets/device-animations/prism-vortex.webp'), deviceData: require('../../assets/device-animations/prism-vortex.motif') },
  { id: 70, name: 'Emerald Radar', category: 'Motion', framed: true, image: require('../../assets/device-animations/emerald-radar.webp'), deviceData: require('../../assets/device-animations/emerald-radar.motif') },
  { id: 71, name: 'Violet Iris', category: 'Motion', framed: true, image: require('../../assets/device-animations/violet-iris-real.webp'), deviceData: require('../../assets/device-animations/violet-iris-real.motif') },
  { id: 72, name: 'Curious Raccoon', category: 'Characters', framed: true, image: require('../../assets/device-animations/curious-raccoon.webp'), deviceData: require('../../assets/device-animations/curious-raccoon.motif') },
  { id: 73, name: 'BMW Roundel', category: 'Emblems', framed: true, image: require('../../assets/device-animations/bmw-roundel.webp'), deviceData: require('../../assets/device-animations/bmw-roundel.motif') },
] as const;

export type GalleryItem = (typeof galleryItems)[number];
export type GalleryCategory = GalleryItem['category'];

export const galleryArt = galleryItems.map((item) => item.image);
export const toyotaAnimation = galleryItems[66];
export const loadingAnimation = galleryItems[67];
export const badgeLoadingAnimation = galleryItems[68];
export const prismVortexAnimation = galleryItems[69];
export const emeraldRadarAnimation = galleryItems[70];
export const violetIrisAnimation = galleryItems[71];
export const curiousRaccoonAnimation = galleryItems[72];
export const bmwAnimation = galleryItems[73];
