export const galleryItems = [
  { id: 0, name: 'Smiley', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/smiley.gif') },
  { id: 1, name: 'Crimson Eye', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/itachi.gif') },
  { id: 2, name: 'Rorschach', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/goat.gif') },
  { id: 3, name: '50 Year', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/50-year-gif.gif') },
  { id: 4, name: 'Omnitrix', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/omnitrix.gif') },
  { id: 5, name: 'Japan', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/japan.gif') },
  { id: 6, name: 'BIM', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/bim.gif') },
  { id: 7, name: 'Quiet', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/quiet.gif') },
  { id: 8, name: 'Level Ten', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/level-ten.gif') },
  { id: 9, name: 'Nocta', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/nocta.gif') },
  { id: 10, name: 'Fleur', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/fleur.gif') },
  { id: 11, name: 'Quiet Red', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/quiet-red.gif') },
  { id: 12, name: 'Challenger', category: 'Emblems', framed: true, image: require('../../assets/demo-gifs/challenger.gif') },
  { id: 13, name: '100', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-100.gif') },
  { id: 14, name: 'Alien Monster', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-alien-monster.gif') },
  { id: 15, name: 'Alien', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-alien.gif') },
  { id: 16, name: 'Basketball', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-basketball.gif') },
  { id: 17, name: 'Beating Heart', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-beating-heart.gif') },
  { id: 18, name: 'Bomb', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-bomb.gif') },
  { id: 19, name: 'Broken Heart', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-broken-heart.gif') },
  { id: 20, name: 'Chequered Flag', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-chequered-flag.gif') },
  { id: 21, name: 'Clown', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-clown.gif') },
  { id: 22, name: 'Collision', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-collision.gif') },
  { id: 23, name: 'Cowboy', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-cowboy.gif') },
  { id: 24, name: 'Crown', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-crown.gif') },
  { id: 25, name: 'Cyclone', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-cyclone.gif') },
  { id: 26, name: 'Dragon', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-dragon.gif') },
  { id: 27, name: 'Eye', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-eye.gif') },
  { id: 28, name: 'Eyes', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-eyes.gif') },
  { id: 29, name: 'Fire Heart', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-fire-heart.gif') },
  { id: 30, name: 'Fire', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-fire.gif') },
  { id: 31, name: 'Fox Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-fox-face.gif') },
  { id: 32, name: 'Ghost', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-ghost.gif') },
  { id: 33, name: 'Glowing Star', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-glowing-star.gif') },
  { id: 34, name: 'Grin Sweat', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-grin-sweat.gif') },
  { id: 35, name: 'Heart Eyes', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-heart-eyes.gif') },
  { id: 36, name: 'Hot Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-hot-face.gif') },
  { id: 37, name: 'Imp Smile', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-imp-smile.gif') },
  { id: 38, name: 'Lion Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-lion-face.gif') },
  { id: 39, name: 'Metal', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-metal.gif') },
  { id: 40, name: 'Mind Blown', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-mind-blown.gif') },
  { id: 41, name: 'Moon Face Full', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-moon-face-full.gif') },
  { id: 42, name: 'Motorcycle', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-motorcycle.gif') },
  { id: 43, name: 'Muscle', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-muscle.gif') },
  { id: 44, name: 'Musical Notes', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-musical-notes.gif') },
  { id: 45, name: 'Party Popper', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-party-popper.gif') },
  { id: 46, name: 'Police Car Light', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-police-car-light.gif') },
  { id: 47, name: 'Racing Car', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-racing-car.gif') },
  { id: 48, name: 'Rage', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-rage.gif') },
  { id: 49, name: 'Red Heart', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-red-heart.gif') },
  { id: 50, name: 'Robot', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-robot.gif') },
  { id: 51, name: 'Rocket', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-rocket.gif') },
  { id: 52, name: 'Rolling Eyes', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-rolling-eyes.gif') },
  { id: 53, name: 'Skull', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-skull.gif') },
  { id: 54, name: 'Smiley Cat', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-smiley-cat.gif') },
  { id: 55, name: 'Soccer Ball', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-soccer-ball.gif') },
  { id: 56, name: 'Sparkles', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-sparkles.gif') },
  { id: 57, name: 'Star Struck', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-star-struck.gif') },
  { id: 58, name: 'Sun With Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-sun-with-face.gif') },
  { id: 59, name: 'Sunglasses Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-sunglasses-face.gif') },
  { id: 60, name: 'Tiger', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-tiger.gif') },
  { id: 61, name: 'Trophy', category: 'Motion', framed: false, image: require('../../assets/demo-gifs/noto-trophy.gif') },
  { id: 62, name: 'Unicorn', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-unicorn.gif') },
  { id: 63, name: 'Victory', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-victory.gif') },
  { id: 64, name: 'Warning', category: 'Symbols', framed: false, image: require('../../assets/demo-gifs/noto-warning.gif') },
  { id: 65, name: 'Zany Face', category: 'Characters', framed: false, image: require('../../assets/demo-gifs/noto-zany-face.gif') },
] as const;

export type GalleryItem = (typeof galleryItems)[number];
export type GalleryCategory = GalleryItem['category'];

export const galleryArt = galleryItems.map((item) => item.image);
